### ISSUE TITLE
How can I evaluate on test data without annotation(metainfo)?

### ISSUE THREAD

**Issue by ta3h30nk1m** [SysCV/shift-detection-tta#12]
I followed all the instructions to train the model, and I validate the performance using validation video data.
I wanted to make submission file by evaluating on test video data, but I found out there is no det_2d.json file for test data.
I checked the dataset downlaoding url (https://dl.cv.ethz.ch/shift/continuous/videos/1x/test/front/) but there is no annotation file for test data.
Your sciprts use annotation data for validation and testing .
Without the annotation file, the error occurs and fail to load dataset.
Where can I get det_2d.json file for test data?
It seems I need annotation json file that at least contains meta information of test data to load on dataset.
Or How can I run test evaluation without annotation file?
Please help me.
Thank you.

**Comment by mattiasegu** [comment]
Hi @ta3h30nk1m, thank you very much for reaching out and reporting the problem. It was a problem on our side. We just fixed it, and the json file should now be available.

Good luck!
