### ISSUE TITLE
ImportError: cannot import name 'Transformer' from 'mmdet.models.layers'

### ISSUE THREAD

**Issue by YuyangSunshine** [SysCV/shift-detection-tta#3]
When I run the validation script:
`bash scripts/continuous/no_adap_yolox/val_yolox_shift_from_clear_daytime.sh`

I met a new problem:
```
Traceback (most recent call last):
  File "/home/yuyang/workspace/project/challenge_iccv2023/shift-detection-tta/tools/test.py", line 88, in <module>
    main()
  File "/home/yuyang/workspace/project/challenge_iccv2023/shift-detection-tta/tools/test.py", line 50, in main
    register_all_modules(init_default_scope=False)
  File "/home/yuyang/workspace/project/challenge_iccv2023/shift-detection-tta/shift_tta/utils/setup_env.py", line 25, in register_all_modules
    register_all_mmtrack_modules(init_default_scope=False)
  File "/home/yuyang/miniconda3/envs/shift-tta/lib/python3.9/site-packages/mmtrack/utils/setup_env.py", line 25, in register_all_modules
    import mmtrack.models  # noqa: F401,F403
  File "/home/yuyang/miniconda3/envs/shift-tta/lib/python3.9/site-packages/mmtrack/models/__init__.py", line 14, in <module>
    from .track_heads import *  # noqa: F401,F403
  File "/home/yuyang/miniconda3/envs/shift-tta/lib/python3.9/site-packages/mmtrack/models/track_heads/__init__.py", line 10, in <module>
    from .stark_head import CornerPredictorHead, StarkHead
  File "/home/yuyang/miniconda3/envs/shift-tta/lib/python3.9/site-packages/mmtrack/models/track_heads/stark_head.py", line 9, in <module>
    from mmdet.models.layers import Transformer
ImportError: cannot import name 'Transformer' from 'mmdet.models.layers'
```

The corresponding versions of mm** is:
Name                    Version                   Build  Channel

> _libgcc_mutex             0.1                        main  
> _openmp_mutex             5.1                       1_gnu  
> addict                    2.4.0                    pypi_0    pypi
> attributee                0.1.8                    pypi_0    pypi
> blas                      1.0                         mkl  
> boto3                     1.26.164                 pypi_0    pypi
> botocore                  1.29.164                 pypi_0    pypi
> brotlipy                  0.7.0           py39h27cfd23_1003  
> bzip2                     1.0.8                h7b6447c_0  
> ca-certificates           2023.05.30           h06a4308_0  
> certifi                   2023.5.7         py39h06a4308_0  
> cffi                      1.15.1           py39h5eee18b_3  
> charset-normalizer        2.0.4              pyhd3eb1b0_0  
> click                     8.1.3                    pypi_0    pypi
> colorama                  0.4.6                    pypi_0    pypi
> contourpy                 1.1.0                    pypi_0    pypi
> cryptography              39.0.1           py39h9ce1e76_2  
> cudatoolkit               11.3.1               h2bc3f7f_2  
> cycler                    0.11.0                   pypi_0    pypi
> cython                    0.29.35                  pypi_0    pypi
> exceptiongroup            1.1.1                    pypi_0    pypi
> ffmpeg                    4.3                  hf484d3e_0    pytorch
> fonttools                 4.40.0                   pypi_0    pypi
> freetype                  2.12.1               h4a9f257_0  
> giflib                    5.2.1                h5eee18b_3  
> gmp                       6.2.1                h295c915_3  
> gnutls                    3.6.15               he1e5248_0  
> h5py                      3.9.0                    pypi_0    pypi
> idna                      3.4              py39h06a4308_0  
> imageio                   2.31.1                   pypi_0    pypi
> importlib-metadata        6.7.0                    pypi_0    pypi
> importlib-resources       5.12.0                   pypi_0    pypi
> iniconfig                 2.0.0                    pypi_0    pypi
> intel-openmp              2023.1.0         hdb19cb5_46305  
> jmespath                  1.0.1                    pypi_0    pypi
> joblib                    1.3.1                    pypi_0    pypi
> jpeg                      9e                   h5eee18b_1  
> kiwisolver                1.4.4                    pypi_0    pypi
> lame                      3.100                h7b6447c_0  
> lap                       0.4.0                    pypi_0    pypi
> lazy-loader               0.2                      pypi_0    pypi
> lcms2                     2.12                 h3be6417_0  
> ld_impl_linux-64          2.38                 h1181459_1  
> lerc                      3.0                  h295c915_0  
> libdeflate                1.17                 h5eee18b_0  
> libffi                    3.4.4                h6a678d5_0  
> libgcc-ng                 11.2.0               h1234567_1  
> libgomp                   11.2.0               h1234567_1  
> libiconv                  1.16                 h7f8727e_2  
> libidn2                   2.3.4                h5eee18b_0  
> libpng                    1.6.39               h5eee18b_0  
> libstdcxx-ng              11.2.0               h1234567_1  
> libtasn1                  4.19.0               h5eee18b_0  
> libtiff                   4.5.0                h6a678d5_2  
> libunistring              0.9.10               h27cfd23_0  
> libuv                     1.44.2               h5eee18b_0  
> libwebp                   1.2.4                h11a3e52_1  
> libwebp-base              1.2.4                h5eee18b_1  
> lz4-c                     1.9.4                h6a678d5_0  
> markdown                  3.4.3                    pypi_0    pypi
> markdown-it-py            3.0.0                    pypi_0    pypi
> matplotlib                3.7.1                    pypi_0    pypi
> mdurl                     0.1.2                    pypi_0    pypi
> mkl                       2023.1.0         h6d00ec8_46342  
> mkl-service               2.4.0            py39h5eee18b_1  
> mkl_fft                   1.3.6            py39h417a72b_1  
> mkl_random                1.2.2            py39h417a72b_1  
> mmcls                     1.0.0rc6                 pypi_0    pypi
**> mmcv                      2.0.0rc4                 pypi_0    pypi
> mmdet                     3.0.0rc6                 pypi_0    pypi
> mmengine                  0.7.4                    pypi_0    pypi
> mmtrack                   1.0.0rc1                 pypi_0    pypi**
> model-index               0.1.11                   pypi_0    pypi
> modelindex                0.0.2                    pypi_0    pypi
> motmetrics                1.4.0                    pypi_0    pypi
> nanoid                    2.0.0                    pypi_0    pypi
> ncurses                   6.4                  h6a678d5_0  
> nettle                    3.7.3                hbbd107a_1  
> networkx                  3.1                      pypi_0    pypi
> numpy                     1.22.4                   pypi_0    pypi
> opencv-python             4.7.0.72                 pypi_0    pypi
> opendatalab               0.0.9                    pypi_0    pypi
> openh264                  2.1.1                h4ff587b_0  
> openmim                   0.3.9                    pypi_0    pypi
> openssl                   3.0.9                h7f8727e_0  
> ordered-set               4.1.0                    pypi_0    pypi
> packaging                 23.1                     pypi_0    pypi
> pandas                    1.3.5                    pypi_0    pypi
> pillow                    9.4.0            py39h6a678d5_0  
> pip                       23.1.2           py39h06a4308_0  
> platformdirs              3.8.0                    pypi_0    pypi
> pluggy                    1.2.0                    pypi_0    pypi
> plyfile                   0.9                      pypi_0    pypi
> psutil                    5.9.5                    pypi_0    pypi
> pycocotools               2.0.6                    pypi_0    pypi
> pycparser                 2.21               pyhd3eb1b0_0  
> pycryptodome              3.18.0                   pypi_0    pypi
> pydantic                  1.10.10                  pypi_0    pypi
> pygments                  2.15.1                   pypi_0    pypi
> pyopenssl                 23.0.0           py39h06a4308_0  
> pyparsing                 3.1.0                    pypi_0    pypi
> pysocks                   1.7.1            py39h06a4308_0  
> pytest                    7.4.0                    pypi_0    pypi
> python                    3.9.16               h955ad1f_3  
> python-dateutil           2.8.2                    pypi_0    pypi
> pytorch                   1.11.0          py3.9_cuda11.3_cudnn8.2.0_0    pytorch
> pytorch-mutex             1.0                        cuda    pytorch
> pytz                      2023.3                   pypi_0    pypi
> pywavelets                1.4.1                    pypi_0    pypi
> pyyaml                    6.0                      pypi_0    pypi
> readline                  8.2                  h5eee18b_0  
> requests                  2.29.0           py39h06a4308_0  
> rich                      13.4.2                   pypi_0    pypi
> s3transfer                0.6.1                    pypi_0    pypi
> scalabel                  0.3.0                    pypi_0    pypi
> scikit-image              0.21.0                   pypi_0    pypi
> scikit-learn              1.3.0                    pypi_0    pypi
> scipy                     1.7.3                    pypi_0    pypi
> seaborn                   0.12.2                   pypi_0    pypi
> setuptools                67.8.0           py39h06a4308_0  
> shapely                   2.0.1                    pypi_0    pypi
> shift-dev                 1.0.0                     dev_0    <develop>
> shift-tta                 0.0.0                     dev_0    <develop>
> six                       1.16.0                   pypi_0    pypi
> sqlite                    3.41.2               h5eee18b_0  
> tabulate                  0.9.0                    pypi_0    pypi
> tbb                       2021.8.0             hdb19cb5_0  
> termcolor                 2.3.0                    pypi_0    pypi
> terminaltables            3.1.10                   pypi_0    pypi
> threadpoolctl             3.1.0                    pypi_0    pypi
> tifffile                  2023.4.12                pypi_0    pypi
> tk                        8.6.12               h1ccaba5_0  
> toml                      0.10.2                   pypi_0    pypi
> tomli                     2.0.1                    pypi_0    pypi
> torchvision               0.12.0               py39_cu113    pytorch
> tqdm                      4.65.0                   pypi_0    pypi
> trackeval                 1.0.dev1                 pypi_0    pypi
> typing_extensions         4.6.3            py39h06a4308_0  
> tzdata                    2023.3                   pypi_0    pypi
> urllib3                   1.26.16          py39h06a4308_0  
> wheel                     0.38.4           py39h06a4308_0  
> xmltodict                 0.13.0                   pypi_0    pypi
> xz                        5.4.2                h5eee18b_0  
> yapf                      0.40.1                   pypi_0    pypi
> zipp                      3.15.0                   pypi_0    pypi
> zlib                      1.2.13               h5eee18b_0  
> zstd                      1.5.5                hc292b87_0

**Comment by mattiasegu** [comment]
Hi, how did you install the environment? 

I've just tested it with the script [tools/install/setup_venv.sh](https://github.com/SysCV/shift-detection-tta/blob/main/tools/install/setup_venv.sh) and it works fine for me.

I also updated the [docs/get_started.md](https://github.com/SysCV/shift-detection-tta/blob/main/docs/get_started.md).

Please try again and let me know if it works!

**Comment by YuyangSunshine** [comment]
Hi, maybe "ssh" can't directly been used.

**Comment by mattiasegu** [comment]
Right, to use ssh you should set up ssh access to github. It's easy but it's an additional step that we can avoid.

I've just pushed a new commit and changed the instructions. Simply removed the ssh part. Please check again [tools/install/setup_venv.sh](https://github.com/SysCV/shift-detection-tta/blob/main/tools/install/setup_venv.sh) or [docs/get_started.md](https://github.com/SysCV/shift-detection-tta/blob/main/docs/get_started.md).

**Comment by YuyangSunshine** [comment]
This works for me! Thanks!
